spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: IMAGE-SERVICE
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image/**
          filters:
            - AuthenticationFilter

        - id: USER-PROFILE
          uri: lb://USER-PROFILE
          predicates:
            - Path=/profile/**
          filters:
            - AuthenticationFilter

        - id: IDENTITY-SERVICE
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka
