spring:
  application:
    name: Gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: IMAGE-SERVICE
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image/**
          filters:
            - AuthenticationFilter

        - id: USER-PROFILE
          uri: lb://USER-PROFILE
          predicates:
            - Path=/profile/**
          filters:
            - AuthenticationFilter

        - id: IDENTITY-SERVICE
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

server:
  port: 8080

#eureka:
#  client:
#    serviceUrl:
##      defaultZone: http://naming-server-service:8761/eureka
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost


#Kubernetes

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
#      podname-{replica-indes}.{service-name}.default.svc.cluster.local

      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka