name: Socials Gateway

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

    - name: Build with Gradle
      run: gradle clean build

#       Till here we have build and test my code

#https://github:com/marketplace/actions/docker-build-push-action:

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
          image: avarm01/socials-gateway
          tags: v1
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
